# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:bookworm
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: django_todo
    volumes:
      - django-pg-data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    expose:
      - 8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/django_todo

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  django-pg-data:
  static_volume:
  media_volume: